# -*- coding: utf-8 -*-
"""desafio_aula8.ipynb

Automatically generated by Colab.

-*- coding: utf-8 -*-

# Análise de dados com Python: Da Preparação à aplicação com Segurança

Projeto: Detecção de Anomalias em Transações em Python



Objetivo:

    Analisar transações financeiras, identificar possíveis anomalias/fraudes
    e comparar modelos de Machine Learning considerando o forte desbalanceamento
    entre transações normais e fraudulentas.

Boas práticas aplicadas:

    - Análise exploratória e validação da qualidade dos dados
    - Separação treino/teste antes de qualquer aprendizado de parâmetros
    - Feature Engineering
    - Pipeline para evitar data leakage
    - Balanceamento somente no conjunto de treinamento
    - Comparação de modelos
    - ROC-AUC e PR-AUC
    - Matriz de confusão
    - Ajuste de threshold
    - Cross-validation e GridSearch
    - Explicabilidade com SHAP
    - Considerações de segurança
"""

# 1. IMPORTAÇÃO DAS BIBLIOTECAS

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    GridSearchCV
)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_auc_score,
    roc_curve,
    precision_recall_curve,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score
)

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

from xgboost import XGBClassifier

# 2. CONFIGURAÇÕES

RANDOM_STATE = 42
TEST_SIZE = 0.30

# Threshold inicial utilizado para classificação de transações suspeitas.
# Será analisado posteriormente para encontrar um ponto adequado.
INITIAL_THRESHOLD = 0.50

# 3. CARREGAMENTO DOS DADOS

URL = "https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"

print("=" * 70)
print("CARREGAMENTO DOS DADOS")
print("=" * 70)

df = pd.read_csv(URL)

print(f"Quantidade de linhas: {df.shape[0]:,}")
print(f"Quantidade de colunas: {df.shape[1]}")
print("\nPrimeiras linhas:")
display(df.head())

# 4. ANÁLISE INICIAL E QUALIDADE DOS DADOS

print("\n" + "=" * 70)
print("QUALIDADE DOS DADOS")
print("=" * 70)

print("\nInformações do dataset:")
df.info()

print("\nValores ausentes por coluna:")
missing = df.isnull().sum()
print(missing[missing > 0] if missing.sum() > 0 else "Nenhum valor ausente.")

print(f"\nQuantidade de linhas duplicadas: {df.duplicated().sum():,}")

print("\nEstatísticas descritivas:")
display(df.describe().T)

# 5. IDENTIFICAÇÃO DA VARIÁVEL-ALVO

TARGET = "Class"

if TARGET not in df.columns:
    raise ValueError(f"A coluna alvo '{TARGET}' não foi encontrada no dataset.")

print("\n" + "=" * 70)
print("DISTRIBUIÇÃO DAS CLASSES")
print("=" * 70)

class_counts = df[TARGET].value_counts().sort_index()
class_percent = df[TARGET].value_counts(normalize=True).sort_index() * 100

distribution = pd.DataFrame({
    "Quantidade": class_counts,
    "Percentual (%)": class_percent.round(4)
})

display(distribution)

print(
    "\nNeste dataset, a classe 0 representa transações normais "
    "e a classe 1 representa transações fraudulentas."
)

# 6. VISUALIZAÇÃO DO DESBALANCEAMENTO

plt.figure(figsize=(7, 5))
df[TARGET].value_counts().sort_index().plot(kind="bar")
plt.title("Distribuição das Transações")
plt.xlabel("Classe")
plt.ylabel("Quantidade")
plt.xticks([0, 1], ["Normal (0)", "Fraude (1)"], rotation=0)
plt.tight_layout()
plt.show()

# 7. ANÁLISE DO VALOR DAS TRANSAÇÕES

print("\n" + "=" * 70)
print("ANÁLISE DO VALOR DAS TRANSAÇÕES")
print("=" * 70)

amount_analysis = df.groupby(TARGET)["Amount"].agg(
    ["count", "mean", "median", "std", "min", "max"]
)

display(amount_analysis)

plt.figure(figsize=(9, 5))
plt.hist(
    df.loc[df[TARGET] == 0, "Amount"],
    bins=50,
    alpha=0.6,
    label="Normal"
)
plt.hist(
    df.loc[df[TARGET] == 1, "Amount"],
    bins=50,
    alpha=0.6,
    label="Fraude"
)
plt.title("Distribuição dos Valores das Transações")
plt.xlabel("Valor da transação")
plt.ylabel("Frequência")
plt.legend()
plt.tight_layout()
plt.show()

# 8. FEATURE ENGINEERING

print("\n" + "=" * 70)
print("FEATURE ENGINEERING")
print("=" * 70)

# Transformação logarítmica para reduzir a influência de valores
# muito elevados na variável Amount.
df["Amount_log"] = np.log1p(df["Amount"])

print("Feature criada: Amount_log")

# 9. SEPARAÇÃO ENTRE FEATURES E TARGET

X = df.drop(columns=[TARGET])
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=TEST_SIZE,
    stratify=y,
    random_state=RANDOM_STATE
)

print("\n" + "=" * 70)
print("DIVISÃO TREINO / TESTE")
print("=" * 70)

print(f"Treino: {X_train.shape[0]:,} registros")
print(f"Teste : {X_test.shape[0]:,} registros")

print("\nDistribuição no treino:")
print(y_train.value_counts(normalize=True).sort_index())

print("\nDistribuição no teste:")
print(y_test.value_counts(normalize=True).sort_index())

# 10. FUNÇÃO DE AVALIAÇÃO

def avaliar_modelo(nome, modelo, X_eval, y_eval, threshold=0.50):
    """
    Avalia um modelo de classificação binária.

    O threshold permite controlar o ponto em que uma transação
    passa a ser considerada suspeita.
    """

    probabilidades = modelo.predict_proba(X_eval)[:, 1]
    previsoes = (probabilidades >= threshold).astype(int)

    roc_auc = roc_auc_score(y_eval, probabilidades)
    pr_auc = average_precision_score(y_eval, probabilidades)

    precision = precision_score(y_eval, previsoes, zero_division=0)
    recall = recall_score(y_eval, previsoes, zero_division=0)
    f1 = f1_score(y_eval, previsoes, zero_division=0)

    print("\n" + "=" * 70)
    print(nome)
    print("=" * 70)

    print(classification_report(
        y_eval,
        previsoes,
        target_names=["Normal", "Fraude"],
        zero_division=0
    ))

    print(f"ROC-AUC : {roc_auc:.4f}")
    print(f"PR-AUC  : {pr_auc:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall   : {recall:.4f}")
    print(f"F1-score : {f1:.4f}")

    return {
        "Modelo": nome,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "ROC-AUC": roc_auc,
        "PR-AUC": pr_auc,
        "Probabilidades": probabilidades,
        "Previsões": previsoes
    }

# 11. MODELO 1 — REGRESSÃO LOGÍSTICA

logistic_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=2000,
        random_state=RANDOM_STATE
    ))
])

logistic_pipeline.fit(X_train, y_train)

resultado_logistic = avaliar_modelo(
    "Regressão Logística",
    logistic_pipeline,
    X_test,
    y_test,
    threshold=INITIAL_THRESHOLD
)

# 12. MODELO 2 — RANDOM FOREST

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    class_weight="balanced",
    n_jobs=-1,
    random_state=RANDOM_STATE
)

rf_model.fit(X_train, y_train)

resultado_rf = avaliar_modelo(
    "Random Forest",
    rf_model,
    X_test,
    y_test,
    threshold=INITIAL_THRESHOLD
)

# 13. MODELO 3 — XGBOOST

# O peso da classe positiva é calculado a partir do conjunto
# de treinamento, evitando definir um valor arbitrário.
scale_pos_weight = (
    (y_train == 0).sum() /
    (y_train == 1).sum()
)

print("\n" + "=" * 70)
print("BALANCEAMENTO DO XGBOOST")
print("=" * 70)

print(f"scale_pos_weight calculado: {scale_pos_weight:.2f}")

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.10,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    eval_metric="logloss",
    random_state=RANDOM_STATE,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

resultado_xgb = avaliar_modelo(
    "XGBoost",
    xgb_model,
    X_test,
    y_test,
    threshold=INITIAL_THRESHOLD
)

# 14. COMPARAÇÃO DOS MODELOS

resultados = pd.DataFrame([
    {
        k: v for k, v in resultado_logistic.items()
        if k not in ["Probabilidades", "Previsões"]
    },
    {
        k: v for k, v in resultado_rf.items()
        if k not in ["Probabilidades", "Previsões"]
    },
    {
        k: v for k, v in resultado_xgb.items()
        if k not in ["Probabilidades", "Previsões"]
    }
])

print("\n" + "=" * 70)
print("COMPARAÇÃO DOS MODELOS")
print("=" * 70)

display(resultados.sort_values("PR-AUC", ascending=False).reset_index(drop=True))

# 15. MATRIZ DE CONFUSÃO — XGBOOST

xgb_predictions = resultado_xgb["Previsões"]

cm = confusion_matrix(y_test, xgb_predictions)

print("\n" + "=" * 70)
print("MATRIZ DE CONFUSÃO — XGBOOST")
print("=" * 70)

print(cm)

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Normal", "Fraude"]
).plot()

plt.title("Matriz de Confusão — XGBoost")
plt.tight_layout()
plt.show()

# 16. CURVA ROC

xgb_probabilities = resultado_xgb["Probabilidades"]

fpr, tpr, _ = roc_curve(y_test, xgb_probabilities)
roc_auc = roc_auc_score(y_test, xgb_probabilities)

plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, label=f"XGBoost — AUC = {roc_auc:.4f}")
plt.plot([0, 1], [0, 1], linestyle="--")
plt.title("Curva ROC — XGBoost")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.tight_layout()
plt.show()

# 17. CURVA PRECISION-RECALL

precision_curve, recall_curve, _ = precision_recall_curve(
    y_test,
    xgb_probabilities
)

pr_auc = average_precision_score(
    y_test,
    xgb_probabilities
)

plt.figure(figsize=(7, 5))
plt.plot(
    recall_curve,
    precision_curve,
    label=f"XGBoost — PR-AUC = {pr_auc:.4f}"
)
plt.title("Curva Precision-Recall — XGBoost")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.legend()
plt.tight_layout()
plt.show()

print(f"PR-AUC do XGBoost: {pr_auc:.4f}")

# 18. ANÁLISE DE THRESHOLD

print("\n" + "=" * 70)
print("ANÁLISE DE THRESHOLD")
print("=" * 70)

thresholds = np.arange(0.10, 1.00, 0.05)

threshold_results = []

for threshold in thresholds:
    predictions = (
        xgb_probabilities >= threshold
    ).astype(int)

    threshold_results.append({
        "Threshold": round(threshold, 2),
        "Precision": precision_score(
            y_test, predictions, zero_division=0
        ),
        "Recall": recall_score(
            y_test, predictions, zero_division=0
        ),
        "F1": f1_score(
            y_test, predictions, zero_division=0
        )
    })

threshold_df = pd.DataFrame(threshold_results)

display(threshold_df)


plt.figure(figsize=(9, 5))
plt.plot(
    threshold_df["Threshold"],
    threshold_df["Precision"],
    marker="o",
    label="Precision"
)
plt.plot(
    threshold_df["Threshold"],
    threshold_df["Recall"],
    marker="o",
    label="Recall"
)
plt.plot(
    threshold_df["Threshold"],
    threshold_df["F1"],
    marker="o",
    label="F1-score"
)

plt.title("Impacto do Threshold nas Métricas")
plt.xlabel("Threshold")
plt.ylabel("Score")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# 19. ESCOLHA DO THRESHOLD PELO MAIOR F1

best_threshold_row = threshold_df.loc[
    threshold_df["F1"].idxmax()
]

BEST_THRESHOLD = float(best_threshold_row["Threshold"])

print("\nThreshold com maior F1-score:")
print(f"Threshold: {BEST_THRESHOLD:.2f}")
print(f"Precision: {best_threshold_row['Precision']:.4f}")
print(f"Recall   : {best_threshold_row['Recall']:.4f}")
print(f"F1-score : {best_threshold_row['F1']:.4f}")

# 20. AVALIAÇÃO FINAL COM O THRESHOLD ESCOLHIDO

final_predictions = (
    xgb_probabilities >= BEST_THRESHOLD
).astype(int)

print("\n" + "=" * 70)
print("AVALIAÇÃO FINAL — XGBOOST")
print("=" * 70)

print(classification_report(
    y_test,
    final_predictions,
    target_names=["Normal", "Fraude"],
    zero_division=0
))

ConfusionMatrixDisplay.from_predictions(
    y_test,
    final_predictions,
    display_labels=["Normal", "Fraude"]
)

plt.title(
    f"Matriz de Confusão — Threshold = {BEST_THRESHOLD:.2f}"
)
plt.tight_layout()
plt.show()

# 21. CROSS-VALIDATION + GRID SEARCH

print("\n" + "=" * 70)
print("AJUSTE DE HIPERPARÂMETROS")
print("=" * 70)

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)

xgb_grid_model = XGBClassifier(
    eval_metric="logloss",
    scale_pos_weight=scale_pos_weight,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [3, 5],
    "learning_rate": [0.05, 0.10],
    "subsample": [0.8, 1.0]
}

grid = GridSearchCV(
    estimator=xgb_grid_model,
    param_grid=param_grid,
    scoring="average_precision",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

grid.fit(X_train, y_train)

print("\nMelhores parâmetros:")
print(grid.best_params_)

print(f"\nMelhor PR-AUC médio na validação: {grid.best_score_:.4f}")

# 22. AVALIAÇÃO DO XGBOOST OTIMIZADO

best_xgb = grid.best_estimator_

resultado_best_xgb = avaliar_modelo(
    "XGBoost Otimizado",
    best_xgb,
    X_test,
    y_test,
    threshold=BEST_THRESHOLD
)

# 23. IMPORTÂNCIA DAS VARIÁVEIS

print("\n" + "=" * 70)
print("IMPORTÂNCIA DAS VARIÁVEIS")
print("=" * 70)

feature_importance = pd.Series(
    best_xgb.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

display(
    feature_importance.head(15).to_frame("Importância")
)

plt.figure(figsize=(10, 6))

feature_importance.head(15).sort_values().plot(
    kind="barh"
)

plt.title("15 Variáveis Mais Importantes — XGBoost")
plt.xlabel("Importância")
plt.ylabel("Variável")
plt.tight_layout()
plt.show()

# 24. EXPLICABILIDADE COM SHAP

print("\n" + "=" * 70)
print("EXPLICABILIDADE — SHAP")
print("=" * 70)

try:
    import shap

    # Amostra limitada para reduzir custo computacional.
    sample_size = min(1000, len(X_test))
    X_shap = X_test.sample(
        sample_size,
        random_state=RANDOM_STATE
    )

    explainer = shap.TreeExplainer(best_xgb)
    shap_values = explainer.shap_values(X_shap)

    print("Importância global das variáveis:")
    shap.summary_plot(
        shap_values,
        X_shap,
        plot_type="bar",
        show=True
    )

    print("Impacto das variáveis nas previsões:")
    shap.summary_plot(
        shap_values,
        X_shap,
        show=True
    )

except ImportError:
    print(
        "SHAP não está instalado. "
        "Instale com: pip install shap"
    )

# 25. SIMULAÇÃO DE UMA TRANSAÇÃO

print("\n" + "=" * 70)
print("SIMULAÇÃO DE DETECÇÃO DE TRANSAÇÃO")
print("=" * 70)

# Utiliza uma transação real do conjunto de teste apenas
# para demonstrar o funcionamento do classificador.
transaction = X_test.iloc[[0]]

transaction_probability = best_xgb.predict_proba(
    transaction
)[0, 1]

transaction_prediction = int(
    transaction_probability >= BEST_THRESHOLD
)

print(f"Probabilidade de fraude: {transaction_probability:.2%}")
print(f"Threshold utilizado: {BEST_THRESHOLD:.2f}")

if transaction_prediction == 1:
    print("Resultado: TRANSAÇÃO SUSPEITA")
else:
    print("Resultado: TRANSAÇÃO NORMAL")

# 26. RESUMO FINAL

final_metrics = {
    "ROC-AUC": roc_auc_score(
        y_test,
        best_xgb.predict_proba(X_test)[:, 1]
    ),
    "PR-AUC": average_precision_score(
        y_test,
        best_xgb.predict_proba(X_test)[:, 1]
    ),
    "Precision": precision_score(
        y_test,
        final_predictions,
        zero_division=0
    ),
    "Recall": recall_score(
        y_test,
        final_predictions,
        zero_division=0
    ),
    "F1-score": f1_score(
        y_test,
        final_predictions,
        zero_division=0
    )
}

print("\n" + "=" * 70)
print("RESUMO FINAL DO PROJETO")
print("=" * 70)

for metric, value in final_metrics.items():
    print(f"{metric:12}: {value:.4f}")

print(f"\nThreshold final: {BEST_THRESHOLD:.2f}")